# Fake terraform for a localhost deployment

- name: Determine hostname
  shell: hostname -f
  register: hostname_complex
  ignore_errors: True

- name: Extract hostanme
  set_fact:
    "node_name": "{{hostname_complex.stdout}}"
    "node_ip": "127.0.0.1"
  delegate_to: localhost
  delegate_facts: true

- name: Add localhost to ansible
  add_host:
    hostname: "localhost"
    groups: hypervisors, primary, etcd_master
