---
# Defaults are Ubuntu specific
shakenfist_deps:
  - arping
  - bridge-utils
  - cpu-checker
  - dnsmasq
  - dnsutils
  - etcd-client
  - git
  - "{{ 'gunicorn3' if ansible_distribution_version < '20.04' else 'gunicorn' }}"
  - libssl-dev
  - libvirt-daemon-system
  - libvirt-dev
  - net-tools
  - prometheus-node-exporter
  - pwgen
  - python3-libvirt
  - qemu-kvm
  - unzip

shakenfist_deps_git_deploy:
  - build-essential
  - python3-dev
  - python3-wheel
  - tox
