---
- name: Ensure unit tests pass
  shell:
    cmd: tox -epy3
    chdir: ../gitrepos/{{repo}}
  tags: unittest

- name: Clear out old wheels
  file:
    path: ../gitrepos/{{repo}}/dist
    state: absent

- name: Ensure we have a local dist directory
  file:
    path: ../gitrepos/{{repo}}/dist
    state: directory

- name: Build a wheel for {{repo}}
  shell:
    cmd: python3 setup.py sdist bdist_wheel
    chdir: ../gitrepos/{{repo}}

- name: Find the most recent wheel for {{repo}}
  shell: ls -rt ../gitrepos/{{repo}}/dist/{{package}}-*.whl | tail -1 | sed 's/\.\.\/gitrepos\/{{repo}}\/dist\///'
  register: wheel_complex

- name: Extract wheel filename
  set_fact:
    "{{package}}_wheel_path": "{{wheel_complex.stdout}}"
